all: Main.class Main.java
	javac Main.java
	java Main

if: IfElse.java
	javac IfElse.java
	java IfElse

mif: IfElseTwo.java
	javac IfElseTwo.java
	java IfElseTwo

sw: Switch.java
	javac Switch.java
	java Switch

fr: For.java
	javac For.java
	java For

ar: Array.java
	javac Array.java
	java Array
